### Get all contacts 
GET http://localhost:3000/users

### Get contants by IDs
GET http://localhost:3000/users/6542bc9ccc322e8b3af6187f
### Get contants by IDs
GET http://localhost:3000/users/6542bd5dcc322e8b3af61880
### Get contants by IDs
GET http://localhost:3000/users/6542bdbecc322e8b3af61881

### Update Contact 
PUT http://localhost:3000/users/6542bc9ccc322e8b3af6187f HTTP/1.1
content-type: application/json

{
  "firstName": "Reagan",
  "LastName": "Houser",
  "email": "houzah@gmail.com",
  "favoriteColor": "pink",
  "birthday": "March 14, 2000"
}

### Update Contact 
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
  "firstName": "Bowen",
  "LastName": "Houser",
  "email": "Bhouser@gmail.com",
  "favoriteColor": "Blue",
  "birthday": "May 4, 1998"
}

### Delete Contact by ID
DELETE http://localhost:3000/users/654bbce83233b2ca6697995b

### Get from live site
GET https://cse341-project1-q5zi.onrender.com/users

### Update Contact 
PUT https://cse341-project1-q5zi.onrender.com/users/6542bc9ccc322e8b3af6187f HTTP/1.1
content-type: application/json

{
  "firstName": "Reagan",
  "LastName": "Houser",
  "email": "houzah@gmail.com",
  "favoriteColor": "Black",
  "birthday": "March 14, 2000"
}

### Update Contact 
POST https://cse341-project1-q5zi.onrender.com/users HTTP/1.1
content-type: application/json

{
  "firstName": "Bowen",
  "LastName": "Houser",
  "email": "Bhouser@gmail.com",
  "favoriteColor": "Blue",
  "birthday": "May 4, 1998"
}

### Delete Contact by ID
DELETE https://cse341-project1-q5zi.onrender.com/users/654e5ae1b952bd3b7d5fefb6
